PACKAGE_NAME="ps5-smu"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="ps5_smu"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^([0-9]+[.]){2}[0-9]+(-ps5.*)?$"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean KDIR=/lib/modules/${kernelver}/build"
